# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laura Pearson | Counselling Service
description: > # this means to ignore newlines until "baseurl:"
  Laura Pearson Counselling Services. Toronto based affliate member of the Ontario Association of counsellors, consultants, psychotherapists and Psychomistraist. Counselling for Addictions, Mental Health, Compassion Fatigue and Life Transitions
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://laurapearsoncounselling.ca" # the base hostname & protocol for your site
images: "http://laurapearsoncounselling.ca/assets/images/"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
